title: Changchang Yin
position: Ph.D. Student
affiliation: The Ohio State University
email: yin.731@osu.edu
keywords: Changchang Yin's homepage
google_scholar: https://scholar.google.com/citations?user=LihEXuMAAAAJ
github_link: https://github.com/yinchangchang/
linkedin: https://www.linkedin.com/yinchangchang/
avatar: ./assets/img/photo.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Changchang Yin's homepage.
canonical: https://yinchangchang.github.io/
remote_theme: yaoyao-liu/minimal-light

theme: jekyll-theme-minimal
